version: '3.1'

services:
  notifier-db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notifier

    ports:
      - 5432:5432

  notifier-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080